/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_penjual;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import model.model_penjual;
import service.service_penjual;
import tabel_model.table_penjual;

/**
 *
 * @author fatiq
 */
public class admin_penjual extends javax.swing.JPanel {

    /**
     * Creates new form admin_pelanggan
     */
    
    private service_penjual servis = new DAO_penjual();
    table_penjual tblMod = new table_penjual();
    
    public admin_penjual() {
        initComponents();
        
        tbl_cont.setModel(tblMod);
        btn_search.requestFocus();
        setColWidht();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        btn_search = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_batal = new rojerusan.RSMaterialButtonRectangle();
        jSeparator1 = new javax.swing.JSeparator();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        btn_hapus = new rojerusan.RSMaterialButtonRectangle();
        tbl_conte = new javax.swing.JScrollPane();
        tbl_cont = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        main.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));
        tampilData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setForeground(new java.awt.Color(0, 0, 0));
        search.setText("Search");
        search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        tampilData.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 350, -1));

        btn_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });
        tampilData.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 32, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Data Penjual");
        tampilData.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        btn_batal.setBackground(new java.awt.Color(0, 0, 0));
        btn_batal.setText("BATAL");
        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        tampilData.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 120, 40));
        tampilData.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 990, 10));

        btn_tambah.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        tampilData.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 40));

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.setText("HAPUS");
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        tampilData.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, 40));

        tbl_cont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_cont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_contMouseClicked(evt);
            }
        });
        tbl_conte.setViewportView(tbl_cont);

        tampilData.add(tbl_conte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 960, 430));

        main.add(tampilData, "card2");

        add(main, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        String x = search.getText();
        if(x.equals("Search")||x.trim().equals("")){
            loadData();
        } else {
            List<model_penjual> list = servis.pencarianData(x);
            tblMod.setData(list);
        }
    }//GEN-LAST:event_btn_searchMouseClicked

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        String x = search.getText().trim();
        if(x.equalsIgnoreCase("")){
            search.setText("Search");
        }
    }//GEN-LAST:event_searchFocusLost

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        String x = search.getText();
        if(x.equalsIgnoreCase("Search")){
            search.setText("");
        }
    }//GEN-LAST:event_searchFocusGained

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String x = btn_tambah.getText();
        int row = tbl_cont.getSelectedRow();
        if(x.equals("TAMBAH")){
            boolean closeable = true;
            tambah_penjual tp = new tambah_penjual(null,closeable);
            tp.setVisible(true);
        }else{
            boolean closeable = true;
            String id = tbl_cont.getModel().getValueAt(row, 1).toString();
            ubah_penjual tp = new ubah_penjual(null,closeable,id);
            tp.setVisible(true);
        }
        loadData();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void tbl_contMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_contMouseClicked
        if(btn_tambah.getText().equals("TAMBAH")){
            btn_tambah.setText("DETAIL");
        }
        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
    }//GEN-LAST:event_tbl_contMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int index = tbl_cont.getSelectedRow();
        if(index != -1){
            model_penjual mod = tblMod.getData(tbl_cont.convertRowIndexToModel(index));
            
            if(JOptionPane.showConfirmDialog(null,"Yakin Data Akan Dihapus","Konfirmasi",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                servis.hapusData(mod);
                tblMod.hapusData(index);
                loadData();
            }
        } else {
            JOptionPane.showMessageDialog(null,"Pilih dahulu record yang akan dihapus");
        }
    }//GEN-LAST:event_btn_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_batal;
    private rojerusan.RSMaterialButtonRectangle btn_hapus;
    private javax.swing.JLabel btn_search;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel main;
    private javax.swing.JTextField search;
    private javax.swing.JPanel tampilData;
    private javax.swing.JTable tbl_cont;
    private javax.swing.JScrollPane tbl_conte;
    // End of variables declaration//GEN-END:variables

    private void setColWidht() {
        int[] noCol = {0,1,2,4,6};
        int[] noColW = {50,90,150,150,90};
        
        TableColumnModel tblModel = tbl_cont.getColumnModel();
        for(int i = 0; i < noCol.length; i++){
        tblModel.getColumn(noCol[i]).setPreferredWidth(noColW[i]);
        tblModel.getColumn(noCol[i]).setMaxWidth(noColW[i]);
        tblModel.getColumn(noCol[i]).setMinWidth(noColW[i]);
        }
    }
    
    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        List<model_penjual> list = servis.ambilData();
        tblMod.setData(list);
        if(btn_tambah.getText().equals("DETAIL")){
            btn_tambah.setText("TAMBAH");
        }
    }
}
