/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.DAO_penjual;
import dao.Encrypt;
import javax.swing.JOptionPane;
import model.model_penjual;
import service.service_penjual;
import tabel_model.table_penjual;

/**
 *
 * @author fatiq
 */
public class gantiPP extends javax.swing.JDialog {

    /**
     * Creates new form gantiFoto
     */
    int xx, xy;
    private service_penjual servis = new DAO_penjual();
    private table_penjual tblMod = new table_penjual();
    public gantiPP(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        lb_id.setText("ID : "+id);
        exit.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JPanel();
        lb_simpan = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        tf_ppL = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_ppB = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tf_ppB2 = new javax.swing.JPasswordField();
        lb_validasiPP = new javax.swing.JLabel();
        cb_y = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ganti Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 410, 47));

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit2.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        btn_simpan.setBackground(new java.awt.Color(0, 0, 255));
        btn_simpan.setMaximumSize(new java.awt.Dimension(0, 0));
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        btn_simpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_simpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_simpan.setForeground(new java.awt.Color(255, 255, 255));
        lb_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_simpan.setText("SIMPAN");
        btn_simpan.add(lb_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 150, -1));

        lb_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_id.setForeground(new java.awt.Color(0, 0, 0));
        lb_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_id.setText("id");
        jPanel1.add(lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 440, -1));
        jPanel1.add(tf_ppL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 390, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password Lama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password Baru");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(tf_ppB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 390, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ulangi Password Baru");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        tf_ppB2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_ppB2FocusLost(evt);
            }
        });
        jPanel1.add(tf_ppB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 390, -1));

        lb_validasiPP.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(lb_validasiPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 230, -1));

        cb_y.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb_y.setForeground(new java.awt.Color(0, 0, 0));
        cb_y.setText("Yakin Mengganti Password");
        jPanel1.add(cb_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 185, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        simpan();
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void tf_ppB2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_ppB2FocusLost
        if(tf_ppB.getText().equals(tf_ppB2.getText())){
            lb_validasiPP.setText("Pasword Sama");
            lb_validasiPP.setForeground(new java.awt.Color(0,255,0));
        } else {
            lb_validasiPP.setText("Pasword Tidak Sama");
            lb_validasiPP.setForeground(new java.awt.Color(255,0,0));
        }
    }//GEN-LAST:event_tf_ppB2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gantiPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gantiPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gantiPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gantiPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gantiPP dialog = new gantiPP(new javax.swing.JFrame(), true, "id");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_simpan;
    private javax.swing.JCheckBox cb_y;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_simpan;
    private javax.swing.JLabel lb_validasiPP;
    private javax.swing.JPasswordField tf_ppB;
    private javax.swing.JPasswordField tf_ppB2;
    private javax.swing.JPasswordField tf_ppL;
    // End of variables declaration//GEN-END:variables

    private void simpan() {
            String[]  x = lb_id.getText().split(":");
            model_penjual modPeng = servis.getByID(x[1].trim());
            String pas = Encrypt.getmd5java(tf_ppL.getText());
            String pass = modPeng.getPassword();
            if(pas.equals(pass)){
                model_penjual bar = new model_penjual();
                String ppP = tf_ppB.getText();
                bar.setId_penjual(x[1].trim());
                bar.setPassword(ppP);
                servis.ubahPassword(bar);
                tblMod.ubahPassword();
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Pasword Lama Salah");
            }
    }

}
