package view;

import dao.DAO_login;
import javax.swing.JOptionPane;
import model.model_login;
import service.service_login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fatiq
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    int xx, xy;
    
    private service_login servis = new DAO_login();
    
    public static boolean tutup = false;
    
    public Login() {
        initComponents();
        
        pn_log.requestFocus();
    }
    
    void bersih(){
        tf_username.setText("username");
        pf_pasword.setText("pasword");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_login = new javax.swing.JPanel();
        lb_exit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        pf_pasword = new javax.swing.JPasswordField();
        pn_log = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.png")).getImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pn_login.setBackground(new java.awt.Color(255, 255, 255));
        pn_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        pn_login.setForeground(new java.awt.Color(255, 255, 255));
        pn_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ex.png"))); // NOI18N
        lb_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitMouseClicked(evt);
            }
        });
        pn_login.add(lb_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock.png"))); // NOI18N
        pn_login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 30, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        pn_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 30, 30));

        tf_username.setForeground(new java.awt.Color(0, 51, 255));
        tf_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_username.setText("Username");
        tf_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        tf_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_usernameFocusLost(evt);
            }
        });
        pn_login.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 30));

        pf_pasword.setForeground(new java.awt.Color(0, 51, 255));
        pf_pasword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pf_pasword.setText("Pasword");
        pf_pasword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        pf_pasword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pf_paswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pf_paswordFocusLost(evt);
            }
        });
        pn_login.add(pf_pasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 30));

        pn_log.setBackground(new java.awt.Color(0, 51, 255));
        pn_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_logMouseClicked(evt);
            }
        });
        pn_log.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("login");
        pn_log.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        pn_login.add(pn_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.png"))); // NOI18N
        pn_login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        pn_login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void lb_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseClicked
        dispose();
    }//GEN-LAST:event_lb_exitMouseClicked

    private void tf_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_usernameFocusGained
        String user = tf_username.getText();
        if (user.equalsIgnoreCase("username")){
            tf_username.setText("");
        }
    }//GEN-LAST:event_tf_usernameFocusGained

    private void pf_paswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pf_paswordFocusGained
        String pp = pf_pasword.getText();
        if (pp.equalsIgnoreCase("pasword")){
            pf_pasword.setText("");
        }
    }//GEN-LAST:event_pf_paswordFocusGained

    private void pf_paswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pf_paswordFocusLost
        String pp = pf_pasword.getText();
        if (pp.equalsIgnoreCase("pasword") || pp.equalsIgnoreCase("")){
            pf_pasword.setText("pasword");
        }
    }//GEN-LAST:event_pf_paswordFocusLost

    private void tf_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_usernameFocusLost
        String user = tf_username.getText();
        if (user.equalsIgnoreCase("username") || user.equalsIgnoreCase("")){
            tf_username.setText("Username");
        }
    }//GEN-LAST:event_tf_usernameFocusLost

    private void pn_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_logMouseClicked
        prosesLogin();
    }//GEN-LAST:event_pn_logMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JPasswordField pf_pasword;
    private javax.swing.JPanel pn_log;
    private javax.swing.JPanel pn_login;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables

    private void prosesLogin() {
        if(validasiIn() == true){
            String ID = tf_username.getText();
            String User = tf_username.getText();
            String pass = pf_pasword.getText();
            
            model.model_login mod_log = new model_login();
            
            mod_log.setId_user(ID);
            mod_log.setNamaUser(User);
            mod_log.setPass(pass);
            
            servis.prosesLogin(mod_log);
            if(tutup){
                dispose();
            }
        }
    }
    
    private boolean validasiIn(){
        boolean valid = false;
        if(tf_username.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        } else if (pf_pasword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }
}
