/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_penjual;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import model.model_penjual;
import service.service_penjual;
import tabel_model.table_penjual;

/**
 *
 * @author fatiq
 */
public class profil_penjual extends javax.swing.JPanel {

    /**
     * Creates new form admin_pelanggan
     */
    
    private service_penjual servis = new DAO_penjual();
    table_penjual tblMod = new table_penjual();
    model_penjual mod;
    
    public profil_penjual(String id) {
        initComponents();
        dataTable(id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_level = new javax.swing.JTextField();
        tf_tlp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lb_img = new rojerusan.RSPanelImage();
        jLabel5 = new javax.swing.JLabel();
        tf_alamat = new javax.swing.JTextField();
        btn_simpan = new rojerusan.RSMaterialButtonRectangle();
        btn_ubahPP = new rojerusan.RSMaterialButtonRectangle();
        btn_ubahFoto = new rojerusan.RSMaterialButtonRectangle();

        setLayout(new java.awt.CardLayout());

        main.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));
        tampilData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Profil Penjual");
        tampilData.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
        tampilData.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 990, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Penjual");
        tampilData.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        tf_id.setEditable(false);
        tf_id.setBackground(new java.awt.Color(255, 255, 255));
        tf_id.setForeground(new java.awt.Color(0, 0, 0));
        tf_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tampilData.add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Username");
        tampilData.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        tf_username.setBackground(new java.awt.Color(255, 255, 255));
        tf_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tampilData.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Alamat");
        tampilData.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        tf_level.setEditable(false);
        tf_level.setBackground(new java.awt.Color(255, 255, 255));
        tf_level.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tampilData.add(tf_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 180, 30));

        tf_tlp.setBackground(new java.awt.Color(255, 255, 255));
        tf_tlp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tampilData.add(tf_tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 440, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NO Telpon");
        tampilData.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        tf_nama.setBackground(new java.awt.Color(255, 255, 255));
        tf_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tampilData.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 440, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama");
        tampilData.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        lb_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lb_img.setImagen(new javax.swing.ImageIcon(getClass().getResource("/img/foto.png"))); // NOI18N

        javax.swing.GroupLayout lb_imgLayout = new javax.swing.GroupLayout(lb_img);
        lb_img.setLayout(lb_imgLayout);
        lb_imgLayout.setHorizontalGroup(
            lb_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lb_imgLayout.setVerticalGroup(
            lb_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tampilData.add(lb_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 260, 250));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Level");
        tampilData.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        tf_alamat.setBackground(new java.awt.Color(255, 255, 255));
        tf_alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tampilData.add(tf_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 440, 30));

        btn_simpan.setBackground(new java.awt.Color(0, 204, 51));
        btn_simpan.setText("SIMPAN");
        btn_simpan.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        tampilData.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 130, 50));

        btn_ubahPP.setBackground(new java.awt.Color(0, 0, 0));
        btn_ubahPP.setText("UBAH PASSWORD");
        btn_ubahPP.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_ubahPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahPPActionPerformed(evt);
            }
        });
        tampilData.add(btn_ubahPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 180, 50));

        btn_ubahFoto.setBackground(new java.awt.Color(0, 0, 0));
        btn_ubahFoto.setText("UBAH FOTO");
        btn_ubahFoto.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_ubahFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahFotoActionPerformed(evt);
            }
        });
        tampilData.add(btn_ubahFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 150, 50));

        main.add(tampilData, "card2");

        add(main, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ubahFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahFotoActionPerformed
        boolean closeable = true;
        gantiFoto gF = new gantiFoto(null,closeable,tf_id.getText());
        gF.setVisible(true);
        dataTable(tf_id.getText());
    }//GEN-LAST:event_btn_ubahFotoActionPerformed

    private void btn_ubahPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahPPActionPerformed
        boolean closeable = true;
        gantiPP gF = new gantiPP(null,closeable,tf_id.getText());
        gF.setVisible(true);
    }//GEN-LAST:event_btn_ubahPPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_simpan;
    private rojerusan.RSMaterialButtonRectangle btn_ubahFoto;
    private rojerusan.RSMaterialButtonRectangle btn_ubahPP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private rojerusan.RSPanelImage lb_img;
    private javax.swing.JPanel main;
    private javax.swing.JPanel tampilData;
    private javax.swing.JTextField tf_alamat;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_level;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_tlp;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables

    private void dataTable(String id) {
        mod = servis.getByID(id);
        
        tf_id.setText(mod.getId_penjual());
        tf_nama.setText(mod.getNama_penjual());
        tf_tlp.setText(mod.getTlp_penjual());
        tf_username.setText(mod.getUsername());
        tf_alamat.setText(mod.getAlamat_penjual());
        tf_level.setText(mod.getLevel());
        
        
        if(mod.getGambar()!=null){
            try{
                byte[] img = mod.getGambar().getBytes(1, (int) mod.getGambar().length());
                ImageIcon imgIcon = new ImageIcon(img);

                lb_img.setImagen(imgIcon);
            }  catch (SQLException ex) {
                Logger.getLogger(ubah_penjual.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
        
    }

}
