/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import custom.JnaFileChooser;
import dao.DAO_penjual;
import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.model_penjual;
import service.service_penjual;
import tabel_model.table_penjual;

/**
 *
 * @author fatiq
 */
public class tambah_penjual extends javax.swing.JDialog {

    /**
     * Creates new form tambah_pelanggan
     */
    
    int xx, xy;
    private service_penjual servis = new DAO_penjual();
    table_penjual tblMod = new table_penjual();
    
    public tambah_penjual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tf_id.setText(servis.nomor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        btn_batal = new rojerusan.RSMaterialButtonRectangle();
        jLabel2 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_tlp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lb_img = new rojerusan.RSPanelImage();
        cb_level = new rojerusan.RSComboMetro();
        jLabel7 = new javax.swing.JLabel();
        tf_alamat = new javax.swing.JTextField();
        lb_namaImg = new javax.swing.JTextField();
        btn_img = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pf_pp = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        pf_pp2 = new javax.swing.JPasswordField();
        lb_validasiPP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit2.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambah Data Penjual");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 670, 47));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        btn_tambah.setBackground(new java.awt.Color(0, 204, 51));
        btn_tambah.setText("SIMPAN");
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 120, 40));

        btn_batal.setBackground(new java.awt.Color(255, 0, 0));
        btn_batal.setText("BATAL");
        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 120, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Penjual");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        tf_id.setEditable(false);
        tf_id.setBackground(new java.awt.Color(255, 255, 255));
        tf_id.setForeground(new java.awt.Color(0, 0, 0));
        tf_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 30));

        tf_nama.setBackground(new java.awt.Color(255, 255, 255));
        tf_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        tf_username.setBackground(new java.awt.Color(255, 255, 255));
        tf_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Level");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        tf_tlp.setBackground(new java.awt.Color(255, 255, 255));
        tf_tlp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(tf_tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 260, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NO Telpon");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        lb_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lb_img.setImagen(null);

        javax.swing.GroupLayout lb_imgLayout = new javax.swing.GroupLayout(lb_img);
        lb_img.setLayout(lb_imgLayout);
        lb_imgLayout.setHorizontalGroup(
            lb_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        lb_imgLayout.setVerticalGroup(
            lb_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(lb_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        cb_level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Level-", "Boss", "Staf", "NotLogin" }));
        cb_level.setColorArrow(new java.awt.Color(0, 0, 0));
        cb_level.setColorBorde(new java.awt.Color(0, 0, 0));
        cb_level.setColorFondo(new java.awt.Color(0, 0, 0));
        cb_level.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(cb_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        tf_alamat.setBackground(new java.awt.Color(255, 255, 255));
        tf_alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(tf_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 260, 30));

        lb_namaImg.setBackground(new java.awt.Color(204, 204, 204));
        lb_namaImg.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lb_namaImg.setForeground(new java.awt.Color(0, 0, 0));
        lb_namaImg.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lb_namaImg.setToolTipText("");
        lb_namaImg.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(lb_namaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 110, 20));

        btn_img.setBackground(new java.awt.Color(255, 255, 255));
        btn_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btn_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imgActionPerformed(evt);
            }
        });
        jPanel1.add(btn_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 40, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Alamat");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        pf_pp.setBackground(new java.awt.Color(255, 255, 255));
        pf_pp.setForeground(new java.awt.Color(0, 0, 0));
        pf_pp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(pf_pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 180, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ulang Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        pf_pp2.setBackground(new java.awt.Color(255, 255, 255));
        pf_pp2.setForeground(new java.awt.Color(0, 0, 0));
        pf_pp2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pf_pp2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pf_pp2MouseMoved(evt);
            }
        });
        jPanel1.add(pf_pp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 180, -1));

        lb_validasiPP.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lb_validasiPP.setToolTipText("");
        jPanel1.add(lb_validasiPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 346, 180, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        if(validasiIn()){
            String id = tf_id.getText();
            String nama = tf_nama.getText();
            String tlp = tf_tlp.getText();
            String usrname = tf_username.getText();
            String alamat = tf_alamat.getText();
            String level = cb_level.getSelectedItem().toString();
            String pass = pf_pp.getText();
            String imgPath = lb_namaImg.getText();

            model_penjual mod = new model_penjual();

            mod.setId_penjual(id);
            mod.setNama_penjual(nama);
            mod.setUsername(usrname);
            mod.setTlp_penjual(tlp);
            mod.setAlamat_penjual(alamat);
            mod.setLevel(level);
            mod.setPassword(pass);
            mod.setImgPath(imgPath);

            servis.tambahData(mod);
            if(!imgPath.trim().isEmpty())
                servis.ubahFoto(mod);
            
            tblMod.tambahData(mod);
            dispose();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void btn_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imgActionPerformed
        select();
    }//GEN-LAST:event_btn_imgActionPerformed

    private void pf_pp2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_pp2MouseMoved
        String x = pf_pp.getText();                          
        String y = pf_pp2.getText();
        if((!"".equals(x)) && (!"".equals(y))){
            if(x.equals(y)){
                lb_validasiPP.setText("Pasword Sama");
                lb_validasiPP.setForeground(new java.awt.Color(0,255,0));
            } else {
                lb_validasiPP.setText("Pasword Tidak Sama");
                lb_validasiPP.setForeground(new java.awt.Color(255,0,0));
            }
        }
    }//GEN-LAST:event_pf_pp2MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tambah_penjual dialog = new tambah_penjual(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_batal;
    private javax.swing.JButton btn_img;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private rojerusan.RSComboMetro cb_level;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSPanelImage lb_img;
    private javax.swing.JTextField lb_namaImg;
    private javax.swing.JLabel lb_validasiPP;
    private javax.swing.JPasswordField pf_pp;
    private javax.swing.JPasswordField pf_pp2;
    private javax.swing.JTextField tf_alamat;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_tlp;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
    
    private void select() {
        JnaFileChooser fileChos = new JnaFileChooser();
        Window window = null;
        boolean action = fileChos.showOpenDialog(window);
        if (action){
            System.out.println(fileChos.getSelectedFile());
            File selectFile = fileChos.getSelectedFile();
            String path = selectFile.getAbsolutePath();
            lb_namaImg.setText(path);
            
            try{
                byte[] img = Files.readAllBytes(selectFile.toPath());
                ImageIcon imgIcon = new ImageIcon(img);

                int lbW = 100;
                int lbH = 100;

                int imgW = imgIcon.getIconWidth();
                int imgH = imgIcon.getIconHeight();

                double scaleX   = (double) lbW / (double) imgW;
                double scaleY   = (double) lbH / (double) imgH;
                double scale    = Math.min(scaleX, scaleY);

                Image scaleImg = imgIcon.getImage().getScaledInstance((int) (scale * imgW), (int) (scale * imgH),Image.SCALE_SMOOTH);

                
                lb_img.setImagen(new ImageIcon(scaleImg));
            }  catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    private boolean validasiIn(){
        boolean valid = false;
        if(tf_id.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID tidak boleh kosong");
        } else if (tf_nama.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong");
        } else if (tf_username.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        } else if (pf_pp.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pasword tidak boleh kosong");
        } else if (!pf_pp.getText().trim().equals(pf_pp2.getText().trim())){
            JOptionPane.showMessageDialog(null, "Pasword tidak sama");
        } else if (tf_alamat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong");
        } else if (cb_level.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Level tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }
}
