/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.koneksi;
import dao.DAO_barang;
import dao.DAO_detailSupplay;
import dao.DAO_laporan;
import dao.DAO_sementara;
import dao.DAO_supplay;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import model.model_barang;
import model.model_detailSupplay;
import model.model_penjual;
import model.model_sementara;
import model.model_supplay;
import model.model_supplayer;
import service.service_barang;
import service.service_detailSupplay;
import service.service_laporan;
import service.service_sementara;
import service.service_supplay;
import tabel_model.table_detailSupplay;
import tabel_model.table_sementara;
import tabel_model.table_supplay;

/**
 *
 * @author fatiq
 */
public class transaksi_supplay extends javax.swing.JPanel {

    /**
     * Creates new form admin_pelanggan
     */
    
    private service_supplay servis = new DAO_supplay();
    table_supplay mod = new table_supplay();
    
    private service_detailSupplay servisD = new DAO_detailSupplay();
    table_detailSupplay modD = new table_detailSupplay();
    
    private service_sementara servisS = new DAO_sementara();
    table_sementara modS = new table_sementara();
    
    private service_barang servisB = new DAO_barang();
    private service_laporan servisL = new DAO_laporan();
    
    public String IDPJ = null;
    
    public transaksi_supplay(String id) {
        initComponents();
        IDPJ = id;
        tbl_cont.setModel(mod);
        tbl_det.setModel(modD);
        tbl_cont1.setModel(modS);
        btn_search.requestFocus();
        setColWidht();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        btn_search = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        pn_det = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_det = new javax.swing.JTable();
        tf_noPesanan1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tf_total1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_tgl1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_namaPen = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_namaPel1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btn_cls = new javax.swing.JLabel();
        tbl_conte = new javax.swing.JScrollPane();
        tbl_cont = new javax.swing.JTable();
        btn_print = new rojerusan.RSMaterialButtonRectangle();
        pesan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_batal = new rojerusan.RSMaterialButtonRectangle();
        tbl_conte1 = new javax.swing.JScrollPane();
        tbl_cont1 = new javax.swing.JTable();
        btn_simpan = new rojerusan.RSMaterialButtonRectangle();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_noPesanan = new javax.swing.JTextField();
        tf_tanggal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tf_total = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_idPel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_pilihP = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_namaPel = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_kodeB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_pilihB = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tf_namaB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_harga = new javax.swing.JTextField();
        tf_jumlah = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_subtotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_tambahB = new rojerusan.RSMaterialButtonRectangle();
        btn_hapus = new rojerusan.RSMaterialButtonRectangle();
        btn_perbarui = new rojerusan.RSMaterialButtonRectangle();

        setLayout(new java.awt.CardLayout());

        main.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));
        tampilData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setForeground(new java.awt.Color(0, 0, 0));
        search.setText("Search");
        search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        tampilData.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 350, -1));

        btn_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });
        tampilData.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 32, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Supplay");
        tampilData.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
        tampilData.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 990, 10));

        btn_tambah.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah.setText(" TAMBAH SUPPLAY");
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        tampilData.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 40));

        pn_det.setBackground(new java.awt.Color(255, 255, 255));
        pn_det.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn_det.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_det.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_det);

        pn_det.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 62, 970, 120));

        tf_noPesanan1.setEditable(false);
        tf_noPesanan1.setBackground(new java.awt.Color(204, 204, 204));
        tf_noPesanan1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_noPesanan1.setForeground(new java.awt.Color(153, 153, 153));
        pn_det.add(tf_noPesanan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("NO Supplay");
        pn_det.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_total1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_total1.setForeground(new java.awt.Color(0, 0, 0));
        tf_total1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tf_total1.setText("Total");
        jPanel8.add(tf_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 260, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Total");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        pn_det.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 360, 30));

        tf_tgl1.setEditable(false);
        tf_tgl1.setBackground(new java.awt.Color(204, 204, 204));
        tf_tgl1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_tgl1.setForeground(new java.awt.Color(153, 153, 153));
        pn_det.add(tf_tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 120, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Tanggal");
        pn_det.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        tf_namaPen.setEditable(false);
        tf_namaPen.setBackground(new java.awt.Color(204, 204, 204));
        tf_namaPen.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_namaPen.setForeground(new java.awt.Color(153, 153, 153));
        pn_det.add(tf_namaPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 160, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Nama Penjual");
        pn_det.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        tf_namaPel1.setEditable(false);
        tf_namaPel1.setBackground(new java.awt.Color(204, 204, 204));
        tf_namaPel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_namaPel1.setForeground(new java.awt.Color(153, 153, 153));
        pn_det.add(tf_namaPel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 160, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Nama Supplayer");
        pn_det.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        btn_cls.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cls.setForeground(new java.awt.Color(0, 0, 0));
        btn_cls.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cls.setText("x");
        btn_cls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clsMouseClicked(evt);
            }
        });
        pn_det.add(btn_cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 20, 20));

        tampilData.add(pn_det, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 1000, 250));

        tbl_cont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_cont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_contMouseClicked(evt);
            }
        });
        tbl_conte.setViewportView(tbl_cont);

        tampilData.add(tbl_conte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 980, 430));

        btn_print.setBackground(new java.awt.Color(0, 204, 51));
        btn_print.setText("PRINT");
        btn_print.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        tampilData.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 140, 40));

        main.add(tampilData, "card2");

        pesan.setBackground(new java.awt.Color(255, 255, 255));
        pesan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Supplay");
        pesan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
        pesan.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1010, 10));

        btn_batal.setBackground(new java.awt.Color(255, 0, 0));
        btn_batal.setText("BATAL");
        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        pesan.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 120, 30));

        tbl_cont1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_cont1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cont1MouseClicked(evt);
            }
        });
        tbl_conte1.setViewportView(tbl_cont1);

        pesan.add(tbl_conte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 700, 420));

        btn_simpan.setBackground(new java.awt.Color(0, 0, 255));
        btn_simpan.setText("SIMPAN");
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        pesan.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 120, 30));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NO Pesanan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tf_noPesanan.setEditable(false);
        tf_noPesanan.setBackground(new java.awt.Color(204, 204, 204));
        tf_noPesanan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_noPesanan.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(tf_noPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        tf_tanggal.setEditable(false);
        tf_tanggal.setBackground(new java.awt.Color(204, 204, 204));
        tf_tanggal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_tanggal.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(tf_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        pesan.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 300, 80));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_total.setForeground(new java.awt.Color(0, 0, 0));
        tf_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tf_total.setText("Total");
        jPanel2.add(tf_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 260, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Total");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        pesan.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 360, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Suppayer");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 300, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        tf_idPel.setEditable(false);
        tf_idPel.setBackground(new java.awt.Color(204, 204, 204));
        tf_idPel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_idPel.setForeground(new java.awt.Color(153, 153, 153));
        tf_idPel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(tf_idPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btn_pilihP.setBackground(new java.awt.Color(0, 0, 0));
        btn_pilihP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pilihP.setForeground(new java.awt.Color(255, 255, 255));
        btn_pilihP.setText("...");
        btn_pilihP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihPActionPerformed(evt);
            }
        });
        jPanel3.add(btn_pilihP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 30, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nama");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        tf_namaPel.setEditable(false);
        tf_namaPel.setBackground(new java.awt.Color(204, 204, 204));
        tf_namaPel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_namaPel.setForeground(new java.awt.Color(153, 153, 153));
        tf_namaPel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_namaPel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(tf_namaPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 140, 20));

        pesan.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 300, 90));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Barang");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 300, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        tf_kodeB.setEditable(false);
        tf_kodeB.setBackground(new java.awt.Color(204, 204, 204));
        tf_kodeB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_kodeB.setForeground(new java.awt.Color(153, 153, 153));
        tf_kodeB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(tf_kodeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Kode Barang");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btn_pilihB.setBackground(new java.awt.Color(0, 0, 0));
        btn_pilihB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pilihB.setForeground(new java.awt.Color(255, 255, 255));
        btn_pilihB.setText("...");
        btn_pilihB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihBActionPerformed(evt);
            }
        });
        jPanel5.add(btn_pilihB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 30, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nama Barang");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        tf_namaB.setEditable(false);
        tf_namaB.setBackground(new java.awt.Color(204, 204, 204));
        tf_namaB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_namaB.setForeground(new java.awt.Color(153, 153, 153));
        tf_namaB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(tf_namaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 280, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Harga");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        tf_harga.setEditable(false);
        tf_harga.setBackground(new java.awt.Color(204, 204, 204));
        tf_harga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_harga.setForeground(new java.awt.Color(153, 153, 153));
        tf_harga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(tf_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 280, 20));

        tf_jumlah.setBackground(new java.awt.Color(255, 255, 255));
        tf_jumlah.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_jumlah.setForeground(new java.awt.Color(0, 0, 0));
        tf_jumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(tf_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 280, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Jumlah");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        tf_subtotal.setEditable(false);
        tf_subtotal.setBackground(new java.awt.Color(204, 204, 204));
        tf_subtotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_subtotal.setForeground(new java.awt.Color(153, 153, 153));
        tf_subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_subtotal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tf_subtotalMouseMoved(evt);
            }
        });
        jPanel5.add(tf_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 280, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Subtotal");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        btn_tambahB.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambahB.setText("TAMBAHKAN BARANG");
        btn_tambahB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tambahB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahBActionPerformed(evt);
            }
        });
        jPanel5.add(btn_tambahB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 280, 30));

        pesan.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 300, 270));

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.setText("HAPUS");
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        pesan.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 290, 30));

        btn_perbarui.setBackground(new java.awt.Color(0, 0, 255));
        btn_perbarui.setText("PERBARUI");
        btn_perbarui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_perbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perbaruiActionPerformed(evt);
            }
        });
        pesan.add(btn_perbarui, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 290, 30));

        main.add(pesan, "card2");

        add(main, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        String x = search.getText();
        if(x.equals("Search")||x.trim().equals("")){
            loadData();
        } else {
            List<model_supplay> list = servis.pencarianData(x);
            mod.setData(list);
        }
    }//GEN-LAST:event_btn_searchMouseClicked

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        String x = search.getText().trim();
        if(x.equalsIgnoreCase("")){
            search.setText("Search");
        }
    }//GEN-LAST:event_searchFocusLost

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        String x = search.getText();
        if(x.equalsIgnoreCase("Search")){
            search.setText("");
        }
    }//GEN-LAST:event_searchFocusGained

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        main.removeAll();
        main.repaint();
        main.revalidate();
        
        main.add(pesan);
        main.repaint();
        main.revalidate();
        
        resetForm();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void tbl_contMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_contMouseClicked
        detail();
    }//GEN-LAST:event_tbl_contMouseClicked

    private void tbl_cont1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cont1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_cont1MouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        loadData();
        resetForm();
        tf_idPel.setText("");
        tf_namaPel.setText("");
        servisS.hapusAll();
        List<model_sementara> list = servisS.ambilData();
        modS.setData(list);
        tf_total.setText("0");
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
       if(validIn()){
            simpan();
            tf_idPel.setText("");
            tf_namaPel.setText("");
            servisS.hapusAll();
            List<model_sementara> list = servisS.ambilData();
            modS.setData(list);
            tf_total.setText("0");
       }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_tambahBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahBActionPerformed
       if(tf_idPel.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pelanggan Tidak Boleh Kosong");
        }if(!(tf_jumlah.getText().trim().isEmpty()||tf_kodeB.getText().trim().isEmpty())){
           if(btn_tambahB.getText().equals("TAMBAHKAN PEMBARUAN")){
                btn_tambahB.setText("TAMBAHKAN BARANG");
                btn_hapus.setText("HAPUS");
                setPerbarui();
           }else{
                tambahDet();
           }
       }
        
    }//GEN-LAST:event_btn_tambahBActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        resetForm();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_perbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perbaruiActionPerformed
        perbarui();
        if(btn_tambahB.getText().equals("TAMBAHKAN BARANG")){
            btn_tambahB.setText("TAMBAHKAN PEMBARUAN");
            btn_hapus.setText("BATAL");
        }
    }//GEN-LAST:event_btn_perbaruiActionPerformed

    private void btn_pilihPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihPActionPerformed
        boolean closeable = true;
        data_supplayer tp = new data_supplayer(null,closeable);
        tp.setVisible(true);
        
        tf_idPel.setText(tp.pel.getId_supplayer());
        tf_namaPel.setText(tp.pel.getNama_supplayer());
    }//GEN-LAST:event_btn_pilihPActionPerformed

    private void btn_clsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMouseClicked
        loadData();
    }//GEN-LAST:event_btn_clsMouseClicked

    private void btn_pilihBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihBActionPerformed
        boolean closeable = true;
        data_barang tp = new data_barang(null,closeable);
        tp.setVisible(true);
        
        if(tp.pel.getKode_barang()!=null && btn_tambahB.getText().equals("TAMBAHKAN PEMBARUAN")){
            btn_tambahB.setText("TAMBAHKAN BARANG");
            btn_hapus.setText("HAPUS");
        }
        
        tf_kodeB.setText(tp.pel.getKode_barang());
        tf_namaB.setText(tp.pel.getNama_barang());
        tf_harga.setText(tp.pel.getHarga().toString());
        tf_jumlah.setText("");
    }//GEN-LAST:event_btn_pilihBActionPerformed

    private void tf_subtotalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_subtotalMouseMoved
        String x = tf_jumlah.getText();
        if(!x.equals("")){
            int y = Integer.parseInt(x) * Integer.parseInt(tf_harga.getText());
            tf_subtotal.setText(String.valueOf(y));
        }else{
            tf_subtotal.setText("");
        }
    }//GEN-LAST:event_tf_subtotalMouseMoved

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        String no_sup = tf_noPesanan1.getText();
        if(!no_sup.trim().isEmpty()){
            servisL.lapTranSup(no_sup);
        }
    }//GEN-LAST:event_btn_printActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_batal;
    private javax.swing.JLabel btn_cls;
    private rojerusan.RSMaterialButtonRectangle btn_hapus;
    private rojerusan.RSMaterialButtonRectangle btn_perbarui;
    private javax.swing.JButton btn_pilihB;
    private javax.swing.JButton btn_pilihP;
    private rojerusan.RSMaterialButtonRectangle btn_print;
    private javax.swing.JLabel btn_search;
    private rojerusan.RSMaterialButtonRectangle btn_simpan;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private rojerusan.RSMaterialButtonRectangle btn_tambahB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pesan;
    private javax.swing.JPanel pn_det;
    private javax.swing.JTextField search;
    private javax.swing.JPanel tampilData;
    private javax.swing.JTable tbl_cont;
    private javax.swing.JTable tbl_cont1;
    private javax.swing.JScrollPane tbl_conte;
    private javax.swing.JScrollPane tbl_conte1;
    private javax.swing.JTable tbl_det;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_idPel;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_kodeB;
    private javax.swing.JTextField tf_namaB;
    private javax.swing.JTextField tf_namaPel;
    private javax.swing.JTextField tf_namaPel1;
    private javax.swing.JTextField tf_namaPen;
    private javax.swing.JTextField tf_noPesanan;
    private javax.swing.JTextField tf_noPesanan1;
    private javax.swing.JTextField tf_subtotal;
    private javax.swing.JTextField tf_tanggal;
    private javax.swing.JTextField tf_tgl1;
    private javax.swing.JLabel tf_total;
    private javax.swing.JLabel tf_total1;
    // End of variables declaration//GEN-END:variables

    private void setColWidht() {
        int[] noCol = {0,1,3,5,7};
        int[] noColW = {50,110,100,100,150};
        
        TableColumnModel tblModel = tbl_cont.getColumnModel();
        for(int i = 0; i < noCol.length; i++){
        tblModel.getColumn(noCol[i]).setPreferredWidth(noColW[i]);
        tblModel.getColumn(noCol[i]).setMaxWidth(noColW[i]);
        tblModel.getColumn(noCol[i]).setMinWidth(noColW[i]);
        }
        
        int[] noCol1 = {0,1,3,4};
        int[] noColW1 = {50,90,150,150};
        
        TableColumnModel tblModel1 = tbl_cont1.getColumnModel();
        for(int i = 0; i < noCol1.length; i++){
        tblModel1.getColumn(noCol1[i]).setPreferredWidth(noColW1[i]);
        tblModel1.getColumn(noCol1[i]).setMaxWidth(noColW1[i]);
        tblModel1.getColumn(noCol1[i]).setMinWidth(noColW1[i]);
        }
        
        int[] noCol2 = {0,1,3,4};
        int[] noColW2 = {50,90,150,150};
        
        TableColumnModel tblModel2 = tbl_det.getColumnModel();
        for(int i = 0; i < noCol2.length; i++){
        tblModel2.getColumn(noCol2[i]).setPreferredWidth(noColW2[i]);
        tblModel2.getColumn(noCol2[i]).setMaxWidth(noColW2[i]);
        tblModel2.getColumn(noCol2[i]).setMinWidth(noColW2[i]);
        }
        
    }
    
    private void loadData() {
        List<model_supplay> list = servis.ambilData();
        mod.setData(list);
        pn_det.setVisible(false);
        pesan.setVisible(false);
        btn_print.setVisible(false);
        
        main.removeAll();
        main.repaint();
        main.revalidate();
        
        main.add(tampilData);
        main.repaint();
        main.revalidate();
    }

    private void detail() {
        int row = tbl_cont.getSelectedRow();
        pn_det.setVisible(true);
        btn_print.setVisible(true);
        String no = tbl_cont.getModel().getValueAt(row, 1).toString();
        String tgl = tbl_cont.getModel().getValueAt(row, 2).toString();
        String namaPen = tbl_cont.getModel().getValueAt(row, 4).toString();
        String namaPel = tbl_cont.getModel().getValueAt(row, 6).toString();
        String total = tbl_cont.getModel().getValueAt(row, 7).toString();
        
        tf_noPesanan1.setText(no);
        tf_tgl1.setText(tgl);
        tf_namaPen.setText(namaPen);
        tf_namaPel1.setText(namaPel);
        tf_total1.setText(total);
        
        List<model_detailSupplay> list = servisD.getByID(no);
        modD.setData(list);
        
        tbl_det.setVisible(true);
        
    }

    private void resetForm() {
        Date now = new Date();
        SimpleDateFormat tanggal = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = tanggal.format(now);
        
        tf_noPesanan.setText(servis.nomor());
        tf_tanggal.setText(tgl);
        tf_kodeB.setText("");
        tf_namaB.setText("");
        tf_harga.setText("");
        tf_jumlah.setText("");
        tf_subtotal.setText("");
        
        if(btn_tambahB.getText().equals("TAMBAHKAN PEMBARUAN")){
            btn_tambahB.setText("TAMBAHKAN BARANG");
            btn_hapus.setText("HAPUS");
        }
    }

    private void tambahDet() {
        String kodeB = tf_kodeB.getText();
        String namaB = tf_namaB.getText();
        int jml = Integer.parseInt(tf_jumlah.getText());
        Long sub = Long.parseLong(tf_subtotal.getText());
        
        model_sementara sem = new model_sementara();
        
        sem.setKode_barang(kodeB);
        sem.setNama_barang(namaB);
        sem.setJumlah(jml);
        sem.setSubtotal(sub);
        
        servisS.tambahData(sem);
        modS.tambahData(sem);
        
        List<model_sementara> list = servisS.ambilData();
        modS.setData(list);
        int total = 0;
        for(int i = 0; i < list.size();i++){
            int C = Integer.parseInt(list.get(i).getSubtotal().toString());
            total = total + C;
        }
        tf_total.setText(String.valueOf(total));
        resetForm();
        
        
    }

    private void simpan() {
        String idPen = IDPJ;
        String idPel = tf_idPel.getText();
        String noPes = tf_noPesanan.getText();
        String tgl = tf_tanggal.getText();
        Long total = Long.parseLong(tf_total.getText());
        
        model_supplay pes = new model_supplay();
        model_penjual pen = new model_penjual();
        model_supplayer pel = new model_supplayer();
        
        pen.setId_penjual(idPen);
        pel.setId_supplayer(idPel);
        
        pes.setId_Pen(pen);
        pes.setId_sup(pel);
        pes.setNo_supplay(noPes);
        pes.setTanggal(tgl);
        pes.setTotal(total);
        
        servis.tambahData(pes);
        
        List<model_sementara> list = servisS.ambilData();
        List listd = new ArrayList();
        for(int i = 0; i < list.size(); i++){
            model_detailSupplay mod1 = new model_detailSupplay();
            model_barang bar = new model_barang();
            
            String kodeBar = list.get(i).getKode_barang();
            int jmlh = list.get(i).getJumlah();
            bar.setKode_barang(kodeBar);
            
            mod1.setId_Pen(pen);
            mod1.setId_sup(pel);
            mod1.setNo_sup(pes);
            mod1.setKode_bar(bar);
            mod1.setJumlah(jmlh);
            mod1.setSubtotal(list.get(i).getSubtotal());
            
            int sisa = servisB.ambilStok(kodeBar);
            int hasil = sisa + jmlh;
            
            servisB.ubahStok(hasil, kodeBar);
            listd.add(mod1);
        }
        
        servisD.tambahData( listd);
        mod.tambahData(pes);
        resetForm();
    }

    private void perbarui() {
        int row = tbl_cont1.getSelectedRow();
        String idB = tbl_cont1.getModel().getValueAt(row, 1).toString();
        int jml = Integer.parseInt(tbl_cont1.getModel().getValueAt(row, 3).toString());
        Long sub = Long.parseLong(tbl_cont1.getModel().getValueAt(row, 4).toString());
        
        model_barang bar = servisB.getByID(idB);
        
        tf_kodeB.setText(idB);
        tf_namaB.setText(bar.getNama_barang());
        tf_harga.setText(bar.getHarga().toString());
        tf_jumlah.setText(String.valueOf(jml));
        tf_subtotal.setText(String.valueOf(sub));
        
        if(btn_tambahB.getText().equals("TAMBAHKAN BARANG")){
            btn_tambahB.setText("TAMBAHKAN PEMBARUAN");
            btn_hapus.setText("BATAL");
        }
    }

    private void setPerbarui() {
        String kodeB = tf_kodeB.getText();
        String namaB = tf_namaB.getText();
        int jml = Integer.parseInt(tf_jumlah.getText());
        Long sub = Long.parseLong(tf_subtotal.getText());
        
        model_sementara sem = new model_sementara();
        
        sem.setKode_barang(kodeB);
        sem.setNama_barang(namaB);
        sem.setJumlah(jml);
        sem.setSubtotal(sub);
        
        servisS.ubahData(sem);
        modS.tambahData(sem);
        
        List<model_sementara> list = servisS.ambilData();
        modS.setData(list);
        int total = 0;
        for(int i = 0; i < list.size();i++){
            int C = Integer.parseInt(list.get(i).getSubtotal().toString());
            total = total + C;
        }
        tf_total.setText(String.valueOf(total));
        resetForm();
    }
    
    private boolean validIn(){
        boolean valid = false;
        if(tf_idPel.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Supplayer Tidak Boleh Kosong");
        }else if(servisS.ambilData().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pesanan Kosong");
        } else {
            valid = true;
        }
        return valid;
    }
}
